### ISSUE TITLE
vipps.CRITICAL: OrderID: XXXXXX. Exception message: Notice: Undefined variable: lockName

### ISSUE THREAD

**Issue by vmalyk** [vippsas/vipps-magento#105]
**Pre-conditions:**
- Magento 2.4.2
- Vipps payment 2.4.17
- PHP 7.4

**Expected result:**
it should be contain correct message.

**Actual result:**
On Fallback endpoint orders get exception in vipps_exeption.log:
`[2021-08-02 18:54:33] vipps.CRITICAL: OrderID: 2000036824 . Exception message: Notice: Undefined variable: lockName in /var/www/www.example.com/www/vendor/vipps/module-payment/Model/TransactionProcessor.php on line 207 [] []
[2021-08-02 18:54:41] vipps.CRITICAL: QuoteID: . Exception message: Notice: Undefined variable: lockName in /var/www/api.floyd.no/www/vendor/vipps/module-payment/Model/TransactionProcessor.php on line 207. Stack Trace #0 /var/www/api.floyd.no/www/vendor/vipps/module-payment/Model/TransactionProcessor.php(207): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined varia...', '/var/www/api.fl...', 207, Array)
#1 /var/www/api.floyd.no/www/vendor/vipps/module-payment/Controller/Payment/Fallback.php(181): Vipps\Payment\Model\TransactionProcessor->process(Object(Vipps\Payment\Model\Quote))
#2 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(58): Vipps\Payment\Controller\Payment\Fallback->execute()
#3 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(138): Vipps\Payment\Controller\Payment\Fallback\Interceptor->___callParent('execute', Array)
#4 /var/www/api.floyd.no/www/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Vipps\Payment\Controller\Payment\Fallback\Interceptor->Magento\Framework\Interception\{closure}()
#5 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute(Object(Vipps\Payment\Controller\Payment\Fallback\Interceptor), Object(Closure))
#6 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(153): Vipps\Payment\Controller\Payment\Fallback\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/api.floyd.no/www/generated/code/Vipps/Payment/Controller/Payment/Fallback/Interceptor.php(23): Vipps\Payment\Controller\Payment\Fallback\Interceptor->___callPlugins('execute', Array, Array)
#8 /var/www/api.floyd.no/www/vendor/magento/framework/App/FrontController.php(188): Vipps\Payment\Controller\Payment\Fallback\Interceptor->execute()
#9 /var/www/api.floyd.no/www/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Vipps\Payment\Controller\Payment\Fallback\Interceptor))
#10 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#12 /var/www/api.floyd.no/www/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/api.floyd.no/www/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/api.floyd.no/www/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#18 /var/www/api.floyd.no/www/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#20 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#21 /var/www/api.floyd.no/www/vendor/convert/module-flow/Plugin/Framework/App/PushEvents.php(53): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(135): Convert\Flow\Plugin\Framework\App\PushEvents->aroundLaunch(Object(Magento\Framework\App\Http\Interceptor), Object(Closure))
#23 /var/www/api.floyd.no/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#24 /var/www/api.floyd.no/www/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, NULL)
#25 /var/www/api.floyd.no/www/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#26 /var/www/api.floyd.no/www/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#27 {main} [] []`

**Comment by voleye** [comment]
Hi @vmalyk thank you for this request, issues solved in v 2.4.18.
