### ISSUE TITLE
Phone isn't pre-filled if Vipps is configured as  Extra Payment in Klarna Checkout 

### ISSUE THREAD

**Issue by vmalyk** [vippsas/vipps-magento#106]
**Pre-conditions:**
1. Magento 2.4.2
2. PHP 7.4
3. Vipps Payment 2.4.17
4. Klarna  Checkout  9.2.1
5. Vipps is configured as extra payment

**Steps to reproduce:** 
1. Add products to cart
2. Fill data in Klarna Iframe - billing address
3. Choose Payment option "Vipps"

**Expected result:**
Phone number should be pre-filled from billing address data

 **Actual result:**
After redirect to Vipps landing page - phone is field:
![image](https://user-images.githubusercontent.com/5318027/129678788-3ad28cd4-e4ff-4d87-839a-a6700c623cbc.png)

Issue is related with format that KCO stored phonenumber in Billing Address - it contains country code (+47) and spaces between number groups, like: +47 401 23 456, but landing page is works with number. Look like it works by the same way for all custom checkouts and the best way for fixing - format data on Initiate data and strip spaces and country code if it's entered  - in this case payment will be work with different checkout and pre-fill will be work as expected.

**Comment by voleye** [comment]
Hi @vmalyk thank you for this request, issues solved in v 2.4.18.
