### ISSUE TITLE
Several errors when run Unit test

### ISSUE THREAD

**Issue by korbax** [vippsas/vipps-magento#107]
Hello please fix issues with the unit test.

-- PHP 7.4
-- Magento 2.4.2
-- vipps/module-payment:2.4.17

`There were 9 errors:

1) Vipps\Payment\Test\Unit\Controller\Payment\FallbackTestTest::testExecuteWithInvalidParams with data set #0 ('00000000001', null)
Error: Call to a member function setPath() on null

/vendor/vipps/module-payment/Controller/Payment/Fallback.php:210
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:235

Caused by
Error: Call to a member function getStore() on null

/vendor/magento/module-checkout/Model/Session.php:338
/vendor/magento/module-checkout/Model/Session.php:361
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:250
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:185
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:235

2) Vipps\Payment\Test\Unit\Controller\Payment\FallbackTestTest::testExecuteWithInvalidParams with data set #1 (null, 'some token')
Error: Call to a member function setPath() on null

/vendor/vipps/module-payment/Controller/Payment/Fallback.php:210
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:235

Caused by
Error: Call to a member function getStore() on null

/vendor/magento/module-checkout/Model/Session.php:338
/vendor/magento/module-checkout/Model/Session.php:361
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:250
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:185
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:235

3) Vipps\Payment\Test\Unit\Controller\Payment\FallbackTestTest::testExecuteWithInvalidParams with data set #2 ('00000000001', 'some token')
Error: Call to a member function setPath() on null

/vendor/vipps/module-payment/Controller/Payment/Fallback.php:210
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:235

Caused by
Error: Call to a member function getStore() on null

/vendor/magento/module-checkout/Model/Session.php:338
/vendor/magento/module-checkout/Model/Session.php:361
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:250
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:185
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:235

4) Vipps\Payment\Test\Unit\Controller\Payment\FallbackTestTest::testCouldNotAcquireLock
Error: Call to a member function setPath() on null

/vendor/vipps/module-payment/Controller/Payment/Fallback.php:210
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:265

Caused by
Error: Call to a member function getStore() on null

/vendor/magento/module-checkout/Model/Session.php:338
/vendor/magento/module-checkout/Model/Session.php:361
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:250
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:185
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:265

5) Vipps\Payment\Test\Unit\Controller\Payment\FallbackTestTest::testTransactionWasCancelled
Error: Call to a member function setPath() on null

/vendor/vipps/module-payment/Controller/Payment/Fallback.php:210
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:298

Caused by
Error: Call to a member function getStore() on null

/vendor/magento/module-checkout/Model/Session.php:338
/vendor/magento/module-checkout/Model/Session.php:361
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:250
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:185
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:298

6) Vipps\Payment\Test\Unit\Controller\Payment\FallbackTestTest::testTransactionWasReservedWhenOrderExists
Error: Call to a member function setPath() on null

/vendor/vipps/module-payment/Controller/Payment/Fallback.php:210
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:346

Caused by
Error: Call to a member function getStore() on null

/vendor/magento/module-checkout/Model/Session.php:338
/vendor/magento/module-checkout/Model/Session.php:361
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:250
/vendor/vipps/module-payment/Controller/Payment/Fallback.php:185
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/FallbackTest.php:346

7) Vipps\Payment\Test\Unit\Controller\Payment\ShippingDetailsTest::testExecuteException
Error: Call to undefined method Mock_RequestInterface_cd9c7f31::getContent()

/vendor/vipps/module-payment/Controller/Payment/ShippingDetails.php:210
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/ShippingDetailsTest.php:297

Caused by
Error: Call to undefined method Mock_RequestInterface_cd9c7f31::getContent()

/vendor/vipps/module-payment/Controller/Payment/ShippingDetails.php:152
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/ShippingDetailsTest.php:297

8) Vipps\Payment\Test\Unit\Controller\Payment\ShippingDetailsTest::testExecuteLocalizedException
Error: Call to undefined method Mock_RequestInterface_cd9c7f31::getContent()

/vendor/vipps/module-payment/Controller/Payment/ShippingDetails.php:210
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/ShippingDetailsTest.php:352

Caused by
Error: Call to undefined method Mock_RequestInterface_cd9c7f31::getContent()

/vendor/vipps/module-payment/Controller/Payment/ShippingDetails.php:152
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/ShippingDetailsTest.php:352

9) Vipps\Payment\Test\Unit\Controller\Payment\ShippingDetailsTest::testExecute
Error: Call to undefined method Mock_RequestInterface_cd9c7f31::getContent()

/vendor/vipps/module-payment/Controller/Payment/ShippingDetails.php:210
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/ShippingDetailsTest.php:480

Caused by
Error: Call to undefined method Mock_RequestInterface_cd9c7f31::getContent()

/vendor/vipps/module-payment/Controller/Payment/ShippingDetails.php:152
/vendor/vipps/module-payment/Test/Unit/Controller/Payment/ShippingDetailsTest.php:480
`

**Comment by voleye** [comment]
Hi @vmalyk thank you for this request, issues solved in v 2.4.18.
