### ISSUE TITLE
Express checkout on product page adding double qty

### ISSUE THREAD

**Issue by sunilkumar771989** [vippsas/vipps-magento#123]
When vipps express checkout button on product page clicked it adds product 2 times so qty gets doubled

**Comment by sunilkumar771989** [comment]
Magento version is 2.4.1 and extension version is 2.4.20

In vipps_exception log vipps.CRITICAL: QuoteID: . Exception message: Type Error occurred when creating object: Magento\Payment\Gateway\Data\Quote\QuoteAdapter, Argument 1 passed to Magento\Payment\Gateway\Data\Quote\QuoteAdapter::__construct() must implement interface Magento\Quote\Api\Data\CartInterface, null given, called in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121. Stack Trace #0 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Payment...', Array)



First time it works fine and next time we get this error There is no varnish cache

**Comment by voleye** [comment]
Hi @sunilkumar771989 could you, please, upgrade to the latest version and report back to us a results. Thanks a lot for this contribution.
