### ISSUE TITLE
Issue with vipps checkout express button Product page

### ISSUE THREAD

**Issue by ABogstad** [vippsas/vipps-magento#124]
Hi, I got issue with vipps checkout express button located on the product page. When pressed it will not load to the checkout window. Instead, when pressing the vipps express button the add to cart button “Legg i handle kurv” is displaying that it is pressed without adding any product to the cart. it is just reloading the product page. Im currently using vipps version:

  "name": "vipps/module-payment",
    "type": "magento2-module",
    "description": "Vipps Payment Method",
    "license": "proprietary",
    "version": "2.4.22",

And the version of magento is 2.4.2

I have attached prinscreen of the inspected element in the webpage:

The vipps log does not show any information. However, the system log and debug log for the whole page shows the following error (I’m nor sure this has anything to do with the issue):

Debug Log
[2022-03-14 10:58:56] main.ERROR: Braintree\Configuration::merchantId needs to be set (or accessToken needs to be passed to Braintree\Gateway). [] []
System log

main.ERROR: Braintree\Configuration::merchantId needs to be set (or accessToken needs to be passed to Braintree\Gateway). [] []

The vipps express button located in the mini cart works fine, no issue there.

I hope you can help me out. Thanks.

![Screen Shot 2022-03-14 at 14 08 44](https://user-images.githubusercontent.com/5305782/158178547-b9a3d09d-7e80-4d9f-b2bd-52262ac9c13a.png)

**Comment by matsjohans** [comment]
Hi, 
If Braintree is not in use for your installation you can try to disable it with the commands described in link below:. 
https://community.magento.com/t5/Magento-2-x-Technical-Issues/Braintree-Error-in-Magento-2-4/td-p/460012
Regards
Mats/Vipps

**Comment by ABogstad** [comment]
This did not solve it. I have seen in the debug logs and error logs and there is nothing information about any errors. No information. 

The version of vipps im using is Vipps_Payment 2.4.22. My webpage is running on Magento 2.4.3.

The vipps express in mini cart works great. The vipps express does not work on product page (Express button under the add to cart button). When vipps button is pressed it just refresh the page. No products is added to the cart either.

**Comment by ABogstad** [comment]
When enabled template hints, 
I see following:

public_html/var/view_preprocessed/pub/static/vendor/magento/module-instant-purchase/view/frontend/templates/button.phtml
public_html/var/view_preprocessed/pub/static/vendor/vipps/module-payment/view/frontend/templates/button.phtml

"Instant Purchase
Instant Purchase allows customers to speed through the checkout process using information that is saved in their account. When enabled, the Instant Purchase button appears below the Add to Cart button on the product page for customers who meet the requirements." - https://docs.magento.com/user-guide/sales/checkout-instant-purchase.html

I have disabled Instant Purchase in backend.

Is there a conflict between Instant Purchase and Vipps Express button?

**Comment by ABogstad** [comment]
I partially solved the issue, I hided the express button on the product detail page. Since the express button works in the minicart, I can live with that solution (express button hidden on product page) for while. Appreciate feedback when you are back.
