### ISSUE TITLE
Magento 2.4.4 issue

### ISSUE THREAD

**Issue by sweikas** [vippsas/vipps-magento#127]
Hey guys, do you have any plans on making the module compatible with magento 2.4.4? Currently module is installable, but during setup:upgrade I get this -> `magento@5ae60fd40301:/var/www/html$ mage set:up
Updating modules:
PHP Fatal error:  Declaration of Vipps\Payment\Model\Logger\Handler\Debug::isHandling(array $record) must be compatible with Monolog\Handler\AbstractHandler::isHandling(array $record): bool in /var/www/html/vendor/vipps/module-payment/Model/Logger/Handler/Debug.php on line 67
`

**Comment by matsjohans** [comment]
Hi, 
Support for 2.4.4 will be released within the next few days. 
Regards
Mats, Vipps

**Comment by sweikas** [comment]
@matsjohans thanks for the quick reply, looking forward to the new release then! :+1:
