### ISSUE TITLE
Vipps payment version Vipps 2.4.33  Division by zero for Configurable items

### ISSUE THREAD

**Issue by vmalyk** [vippsas/vipps-magento#151]
Hi, We upgraded Vipps module to 2.4.33 and if order contains Configurable products We get in logs: 

[2022-11-03 21:39:24] vipps.CRITICAL: Warning: Division by zero in /mnt/floyd_live_volume/www/api.floyd.no/www/vendor/vipps/module-payment/Gateway/Request/SendReceipt/OrderLinesBuilder.php on line 75 [] []

Might be related  with logic of getting items -  parent  items are skipped, but totals are collected on parent item and child has 0 in row, discount and tax totals, as result - $totalAmount = 0 :

https://github.com/vippsas/vipps-magento/blob/bf50d71ef2d94c9b600c848fba86248917421365/Gateway/Request/SendReceipt/OrderLinesBuilder.php#L75

**Comment by voleye** [comment]
Hi @vmalyk thank you for your request, we have created internal ticket to solve this issue. Usually, it takes few days when issue resolved. I will keep you posted. Thanks
