### ISSUE TITLE
Mixed up credentials with multi-website?

### ISSUE THREAD

**Issue by macieklewkowicz** [vippsas/vipps-magento#157]
**Environment**
* Magento 2.4.5-p1
* Vipps module 2.4.41
* Klarna Checkout 9.4.1

**Configuration**
* 2 websites ("Website A", "Website B"); Website A is the `base` website with ID 1
* Each website uses a different set of Vipps credentials
* Vipps:
  * [global]
    * Environment: Develop
    * Payment Action: Authorize and Capture
    * Debug: Yes
    * Credentials: empty
    * Enabled: No
  * [website: Website A] same as [global], except
    * Credentials: intentionally incorrect
    * Enabled: No
  * [website: Website B] same as [global], except
    * Credentials: full and correct
    * Enabled: Yes
    
**Steps to reproduce**
* Place an order and pay via Vipps
* Go to ther order in the admin
* Go to the invoice
* Click "Credit memo"
* Click "Refund" (not "Refund Offline")

**Expected behavour**
* A credit memo is created

**Actual behaviour**
* An error message appears: "Can't retrieve access token from Vipps."
* Credit memo is not created

**Additional notes**
* Checkout works fine on both Website A and Website B
* Both Website A and Website B show up in the Vipps MT app as separate recipients with correct payment history
* When Website A uses it's own correct credentials, the error message for Website B is "Requested Order not found"
* When Website A uses it's own correct credentials, it works entirely as expected (Website B still doesn't)
* When using Payment Action: "Authorize", same errors occur for Website B when trying to invoice the order with online capture

Could it be, that the module is trying to use Website A credentials to process Website B payments in the admin panel?

**Comment by voleye** [comment]
Hi @macieklewkowicz sorry for late response, the fix is ready and currently is on testing phase, I do believe today-tomorrow we will release a new version with fix included in it. I will gat back to you after new version is released. Thanks a lot!

**Comment by voleye** [comment]
Hello @macieklewkowicz let me inform you that new version 2.4.42 with the fix for an issue was released, please update your version of module.
