### ISSUE TITLE
Hyvä Compatibility modul

### ISSUE THREAD

**Issue by thaulow** [vippsas/vipps-magento#158]
Hello,

Have Vipps considered making a combat module for supporting Hyvä? Would be nice for us migrating from Luma to Hyvä, as I am guessing it will be quite many of us in the future, that do not want to go down the PWA Studio road :)

https://gitlab.hyva.io/hyva-public/module-tracker/-/boards

**Comment by matsjohans** [comment]
Hello, 
Sorry for our late reply. 
We dont have plans for making this at the moment, but we see that there is a setting on Hyva that you can enable luma-theme based checkout. It may be possible that this solution will work out of the box.
Regards
Mats,
Vipps
