### ISSUE TITLE
Component Dependency issues in Magento 2.2.7 and 2.3.0 (Framework 102.0.0)

### ISSUE THREAD

**Issue by DigiBlooD** [vippsas/vipps-magento#19]
Hi

Component Dependency gives the following error
- vipps/module-payment 1.0.12 requires magento/framework 101.0.* -> satisfiable by magento/framework[101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.4, 101.0.5, 101.0.6, 101.0.7].
- Can only install one of: magento/framework[102.0.0, 101.0.0].
- Can only install one of: magento/framework[102.0.0, 101.0.1].
- Can only install one of: magento/framework[102.0.0, 101.0.2].
- Can only install one of: magento/framework[102.0.0, 101.0.3].
- Can only install one of: magento/framework[102.0.0, 101.0.4].
- Can only install one of: magento/framework[102.0.0, 101.0.5].
- Can only install one of: magento/framework[102.0.0, 101.0.6].
- Can only install one of: magento/framework[102.0.0, 101.0.7].

Any idea when 102.0.0 support will be added?

**Comment by voleye** [comment]
Hi @DigiBlooD thank you for your report! We are working on it right now and are going to deliver it with next release

**Comment by mlia** [comment]
Got an ETA on this?

**Comment by voleye** [comment]
Hi @mlia Although such fixes are not so complicated we are preparing a complex improvement for background processing of orders that we are planning to finish within ~ 2-3 weeks, more likely we will not deliver the fix for 2.3 support earlier, let us know if it is ok for you.

**Comment by voleye** [comment]
@DigiBlooD Hi, still in progress, the point is that we are working on portions of improvements for module, then, are going to release both versions, updated old version and new version for 2.3.
Approximate period to finalize this is 1-2 weeks

Thanks for your question.

**Comment by voleye** [comment]
**Status update**

We are going to release a new version of module for Magento 2.2.x the day after tomorrow. 
Next priority 1 is to prepare module for 2.3. We expect to finish and release version for 2.3 within 3-5 days.

**Comment by voleye** [comment]
**Status update**

Hi guys, Vipps module compatible with Magento 2.3 now released, https://github.com/vippsas/vipps-magento/releases/tag/1.3.1
