### ISSUE TITLE
Error during installation of version 1.0.14

### ISSUE THREAD

**Issue by Heidishopsystem** [vippsas/vipps-magento#23]
We get the the following error when installing version 1.0.4 on Magento version 2.2.7

`[RuntimeException]
  Source class "\VippsInitiateTransfer" for "VippsInitiateTransferFactory" generation does not exist.`

**Comment by voleye** [comment]
Hi @Heidishopsystem thank you for your feedback, we will check it! To track an issue we have created internal ticket VIPPS-190

**Comment by voleye** [comment]
Hi @Heidishopsystem just FYI, we are going to release a new version of module the day after tomorrow. The release includes fixes for an issue that you described. Also the version includes improved tool to track and manage failed payments from admin panel.

Please, be informed to get upgraded version of module.

**Comment by Heidishopsystem** [comment]
@voleye Thank you!

**Comment by voleye** [comment]
I will close this issue since we released a new version of module 1.2.1
