### ISSUE TITLE
Vipps payments not always registrer an order

### ISSUE THREAD

**Issue by DrKoolaid** [vippsas/vipps-magento#24]
Some times the customer completes the the payment, but no order is created.

[2019-01-28 14:50:06] vipps.CRITICAL: Order has not been placed, quote id: "990", reserved_order_id: "000000319"
and running the the sql from the faq gives:

{"merchant_auth_token":"xxxxxx","fallback_auth_token":"xxxxx","vipps":{"attempts":3,"cancel_reason_phrase":"canceled after \"3\" attempts, last error \"n\/a\"","reserved_order_id":"000000319"}}

Any idea whats happening here?

**Comment by voleye** [comment]
Hi @DrKoolaid thank you for your feedback, we are planning to release a new version of a module the day after tomorrow. The release includes more useful ability to track and manage payment errors from admin panel. It would be nice if you upgrade to that version. Hope it helps to fix or at least to identify your problem.

**Comment by voleye** [comment]
I will close this issue since we released new version of module (1.2.1) that contains Vipps monitoring that aims to solve an issue with missing order in Magento, please feel free to open new issue if you still have some problems with missed orders
