### ISSUE TITLE
Error during installation of version 1.2.1

### ISSUE THREAD

**Issue by Heidishopsystem** [vippsas/vipps-magento#26]
We get the following error during installation of version 1.2.2 via composer: 

The requested package vipps/module-payment 1.2.1 exists as vipps/module-payment[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.2, 1.0.7, 1.0.8, 1.0.9, dev-faq, dev-master, dev-publication-1.0.10, dev-publication-1.0.11, dev-publication-1.0.12, dev-publication-1.0.13, dev-publication-1.0.14, dev-publication-1.0.9] but these are rejected by your constraint.

**Comment by voleye** [comment]
Hi @Heidishopsystem could you please, specify the version of Magento and we will check?

**Comment by voleye** [comment]
Just checked an installation for Magento 2.2.7 CE, by doing following commands:
```
 - git clone https://github.com/magento/magento2.git
 - git checkout 2.2.7
 - composer install
 - composer config repositories.vipps git git@github.com:vippsas/vipps-magento.git
 - composer require vipps/module-payment:1.2.1
```
Works for me, just let me know the version of Magento you are using.
Note: support for Magento 2.3 coming soon (~5 days)

**Comment by farhadfrz** [comment]
Could you please update packagist?
This version (1.2.1) does not exist there!

**Comment by voleye** [comment]
1.2.2 version was uploaded to packagist, so I closed this Issue
