### ISSUE TITLE
Releases 1.2.3, 1.3.1 are not in packagist

### ISSUE THREAD

**Issue by pikulsky** [vippsas/vipps-magento#30]
Releases 1.2.3, 1.3.1 are not in packagist, is it intentionally?

**Comment by pikulsky** [comment]
https://packagist.org/packages/vipps/module-payment

**Comment by aluminium1989** [comment]
Hi @pikulsky 

Thanks for your request.
New versions have been placed to Packagist as well.

**Comment by aluminium1989** [comment]
Please note that 1.3.2 version is also available in Packagist.
It brings a fix for PHP7.1

**Comment by pikulsky** [comment]
great, thank you!
