### ISSUE TITLE
Vipps 1.3.6 - Magento 2.3.1 - Element 'config_path': [facet 'pattern'] The value 'payment/vipps/cancellation/attempts_count' is not accepted by the pattern '[a-zA-Z0-9_]+/[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'.

### ISSUE THREAD

**Issue by xnhinzkyx** [vippsas/vipps-magento#43]
I saw this on admin after I logged in. Please check issue.

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/www/vendor/vipps/module-payment/etc/adminhtml/system.xml" is invalid:
Element 'config_path': [facet 'pattern'] The value 'payment/vipps/cancellation/attempts_count' is not accepted by the pattern '[a-zA-Z0-9_]+/[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'.
Line: 139

Element 'config_path': 'payment/vipps/cancellation/attempts_count' is not a valid value of the atomic type 'typeConfigPath'.
Line: 139

Element 'config_path': [facet 'pattern'] The value 'payment/vipps/cancellation/type' is not accepted by the pattern '[a-zA-Z0-9_]+/[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'.
Line: 148

Element 'config_path': 'payment/vipps/cancellation/type' is not a valid value of the atomic type 'typeConfigPath'.
Line: 148

Element 'config_path': [facet 'pattern'] The value 'payment/vipps/cancellation/quote_storage_period' is not accepted by the pattern '[a-zA-Z0-9_]+/[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'.
Line: 157

Element 'config_path': 'payment/vipps/cancellation/quote_storage_period' is not a valid value of the atomic type 'typeConfigPath'.
Line: 157

Element 'config_path': [facet 'pattern'] The value 'payment/vipps/cancellation/customer_inactivity_time' is not accepted by the pattern '[a-zA-Z0-9_]+/[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'.
Line: 166

Element 'config_path': 'payment/vipps/cancellation/customer_inactivity_time' is not a valid value of the atomic type 'typeConfigPath'.
Line: 166

Verify the XML and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/www/vendor/vipps/module-payment/etc/adminhtml/system.xml" is invalid:
Element 'config_path': [facet 'pattern'] The value 'payment/vipps/cancellation/attempts_count' is not accepted by the pattern '[a-zA-Z0-9_]+/[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'.
Line: 139

Element 'config_path': 'payment/vipps/cancellation/attempts_count' is not a valid value of the atomic type 'typeConfigPath'.
Line: 139

Element 'config_path': [facet 'pattern'] The value 'payment/vipps/cancellation/type' is not accepted by the pattern '[a-zA-Z0-9_]+/[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'.
Line: 148

Element 'config_path': 'payment/vipps/cancellation/type' is not a valid value of the atomic type 'typeConfigPath'.
Line: 148

Element 'config_path': [facet 'pattern'] The value 'payment/vipps/cancellation/quote_storage_period' is not accepted by the pattern '[a-zA-Z0-9_]+/[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'.
Line: 157

Element 'config_path': 'payment/vipps/cancellation/quote_storage_period' is not a valid value of the atomic type 'typeConfigPath'.
Line: 157

Element 'config_path': [facet 'pattern'] The value 'payment/vipps/cancellation/customer_inactivity_time' is not accepted by the pattern '[a-zA-Z0-9_]+/[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'.
Line: 166

Element 'config_path': 'payment/vipps/cancellation/customer_inactivity_time' is not a valid value of the atomic type 'typeConfigPath'.
Line: 166

**Comment by xnhinzkyx** [comment]
I manage to fixed it by just following the pattern.
File: vendor/vipps/module-payment/etc/adminhtml/system/cancellation.xml

From:


            <config_path>payment/vipps/cancellation/attempts_count</config_path>
            <config_path>payment/vipps/cancellation/type</config_path>
            <config_path>payment/vipps/cancellation/quote_storage_period</config_path>
            <config_path>payment/vipps/cancellation/customer_inactivity_time</config_path>
       
To: 

            <config_path>payment/vipps/cancellation_attempts_count</config_path>
            <config_path>payment/vipps/cancellation_type</config_path>
            <config_path>payment/vipps/cancellation_quote_storage_period</config_path>
            <config_path>payment/vipps/cancellation_customer_inactivity_time</config_path>

**Comment by aluminium1989** [comment]
Hi @xnhinzkyx.
Thank you for posting the issue and providing clear details.
Your commit fixes admin interface back but brings another issue to the module.

We are working on the issue and will resolve it next week.

**Comment by emilshamloo** [comment]
I've got the same problem. Please, let me know when it is done!

**Comment by emilshamloo** [comment]
![image](https://user-images.githubusercontent.com/2904897/57182270-83b35680-6e9d-11e9-9138-0c26e7fa4efe.png)

**Comment by aluminium1989** [comment]
The issue has been fixed and updated in Packagist.
