### ISSUE TITLE
Cant Capture anymore

### ISSUE THREAD

**Issue by DrKoolaid** [vippsas/vipps-magento#44]
Hi

Some weeks ago the Capture function stopped working. Maybe after an upgrade to the plugin.

If I now go on a Vipps order and try to invoice we get an error message.
"Vipps payment method does not support Capture Offline"

But why has the order become "Offline payment" ?

Any idea of what to do about it ?

**Comment by cloveras** [comment]
Hi

Thanks for reporting this.

It seems like it may be a network issue on your end, but we will check.

Christian, Vipps

**Comment by aluminium1989** [comment]
@DrKoolaid 

Please share Magento and module versions.

**Comment by DrKoolaid** [comment]
Magento 2.3.1 and we have the latest module version, I upgraded today from 1.3.5 => 1.3.6

**Comment by Solcellespesialisten** [comment]
![vipps_capture_offline_issue](https://user-images.githubusercontent.com/43231235/58152600-41479300-7c6d-11e9-9417-6974caf352b2.png)
We are experiencing a similar problem, also within the last few weeks. We cannot capture and we get this offline error. No changes made to our config. Magento ver. 2.2.8 (CE). We were asked by the Vipps integration team to contact you guys here.

**Comment by aluminium1989** [comment]
Hi @DrKoolaid  and @Solcellespesialisten .
Please reinstall/update the module avoiding cached version.
`composer clear-cache `
`composer update --prefer-source vipps/payment`
And to fix online capturing for already not-working orders please execute this sql query:
`update sales_payment_transaction spt
inner join sales_order_payment as sop on spt.`payment_id` = sop.`parent_id` 
set is_closed = 0
where txn_type = 'authorization' and is_closed = 1 and sop.`method` = 'vipps' and sop.`base_amount_paid_online` IS NULL;` (modify on your risk)

**Comment by cloveras** [comment]
Hi, @Solcellespesialisten 

Can you please let us know if the steps above solves the problem?

Christian, Vipps

**Comment by DrKoolaid** [comment]
Its now working, but we have a bunch of old orders now that has the state/status "Closed" and that we cant do anything whit from admin. So we dont have any way of Capturing those orders.

We have run the sql from over here, but I think maybe that only fixed the order that was not already billed/sent.

Any ide how we can Capture the orders that is now "Closed" ?

**Comment by Solcellespesialisten** [comment]
Hi. As far as I know, this fix solved our issues including older transactions. We did an extention update and ran the sql commands. Thanks

**Comment by DrKoolaid** [comment]
Any idea how to fix this?

We have lots of orders that has the state "Closed" whit an invoice and Shippent. It dont help to just run the Sql recommended over her.  We need to be able to Complete the orders to Capture.

**Comment by DrKoolaid** [comment]
No more help, u will just let ur customer loss all those money ?

**Comment by DrKoolaid** [comment]
the initial problem seems to be. still there. 
Only orders that is not processed is being  fixed whit the sql over here.
But new orders still get the same problem.

**Comment by DrKoolaid** [comment]
On another page we have similar issue now, we get the "Vipps payment method does not support Capture Offline"

We have tried to upgrade the module to 1.3.7 without any changes.
When trying to run this separate after running composer clear-cache, we get this:

prod@prod01:~/www$ composer update --prefer-source vipps/payment
Package "vipps/payment" listed for update is not installed. Ignoring.

When we run the SQL over her we get "0 records affected"

**Comment by voleye** [comment]
Hi @DrKoolaid that is a bit strange, because output says that update is not possible because module is not installed, try to install it first. 

Please follow instruction here https://github.com/vippsas/vipps-magento/blob/master/INSTALL.md
you can manually specify the version e.g.
1. `composer config repositories.vipps git git@github.com:vippsas/vipps-magento.git`
2. `composer require vipps/module-payment:1.3.7`

Do you still have an issue with closed orders?

**Comment by cloveras** [comment]
Hi, @DrKoolaid 

Can you give us an update, please?

Christian, Vipps

**Comment by DrKoolaid** [comment]
The module is ofcource installed already. Even if we get that message that is not.
 I dont know why it saying its not.

When running the command over I get:

prod@prod01:~/www$ composer config repositories.vipps git git@github.com:vippsas/vipps-magento.git
prod@prod01:~/www$ composer require vipps/module-payment:1.3.7
./composer.json has been updated                                          
Loading composer repositories with package information
Updating dependencies (including require-dev)                             
Nothing to install or update


No progress

**Comment by aluminium1989** [comment]
@DrKoolaid,

Please note that module update does not impact existent orders.

It is possible to capture orders that are already captured offline by deleting and re-creating invoices.
And another approach is to ask customers to create new orders. That probably would be better for closed orders.

**Comment by voleye** [comment]
Closed due to inactivity
