### ISSUE TITLE
Can't install using composer with Magento 2.2.8

### ISSUE THREAD

**Issue by asheempatro77** [vippsas/vipps-magento#48]
Hello,

I am getting below error where trying to install Vipps using composer in Magento 2.2.3.

Problem 1
    - Installation request for magento/product-community-edition 2.2.8 -> satisfiable by magento/product-community-edition[2.2.8].
    - vipps/module-payment 1.3.7 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.0, 102.0.1].
    - Can only install one of: magento/framework[101.0.8, 102.0.0].
    - Can only install one of: magento/framework[101.0.8, 102.0.1].
    - magento/product-community-edition 2.2.8 requires magento/framework 101.0.8 -> satisfiable by magento/framework[101.0.8].
    - Installation request for vipps/module-payment 1.3.7 -> satisfiable by vipps/module-payment[1.3.7].

Can I get a solution for this?

**Comment by DrKoolaid** [comment]
I have seen similar issues when installing other plugins, and it has been something my developer have fixed localy. So it dont look like an issues whit the Vipps plugin to me.

**Comment by asheempatro77** [comment]
@DrKoolaid, Please let me know what all things to be done with regards to fix this issue.

**Comment by DrKoolaid** [comment]
Try upgrade to Magento 2.3.1 maybe
