### ISSUE TITLE
Disabled but still showing in store

### ISSUE THREAD

**Issue by erocm123** [vippsas/vipps-magento#49]
I installed the plugin via the instructions, but did not configure it or enable it. It is showing up as an option in our stores. I am going to remove the files because I have not been provided the configuration settings to finish the setup, but shouldn't it be hidden until it is enabled in the Magento configuration?

![image](https://user-images.githubusercontent.com/8661384/61551956-d23fae00-aa13-11e9-8c29-42ba5e3b637d.png)

![image](https://user-images.githubusercontent.com/8661384/61552095-1f238480-aa14-11e9-9e96-ee2603e4ae7b.png)

**Comment by voleye** [comment]
Hi @erocm123 , yes it should be disabled since it is disabled in "System -> Configuration" probably you have a deal with caching

**Comment by voleye** [comment]
Closed due to inactivity
