### ISSUE TITLE
Button placed behind Vipps Checkout button in mini shopping cart on Frontend

### ISSUE THREAD

**Issue by ABogstad** [vippsas/vipps-magento#52]
Hi, I was told by the integration team from Vipps to post my issue here. It seems that after installing the module Vipps, the mini shopping cart on frontend displays a button behind the Vipps Checkout button (see. image). This button is not very nice to see for the potential customer. When this other button is pressed, the visitor redirects do a 404 page, where the url path is www.     .no/undefined

When the vipps Checkout button is pressed, everything works fine. Thanks in advance. Also, when disabling the module Vipps_Payment, the express button is not available anymore on mini cart and the other button is not there either. Which means that the other button is only displayed behind the Express button in minicart when Vipps is enabled.

I have attached print screens of frontend containing template paths and blocks. I can see the the following in the 404 error page (with the undefined path) that the "other button" redirects to after pressing it: 

vendor/amzn/amazon-pay-and-login-with-amazon-core-module/view/frontend/templates/config.phtml

Amazon\Core\Block\Config

I wonder if this can give some clue about what the cause of described issue. I worth mention that the amazon module is disabled in backend. 

 Kind regards, A.

Magento ver. 2.3.3

![Vipps knapp i minicart](https://user-images.githubusercontent.com/5305782/72156377-ae06cd80-33b5-11ea-90c6-9c47a85b69b6.png)

![Screen Shot 2020-01-12 at 12 25 41](https://user-images.githubusercontent.com/5305782/72245459-e8a87a00-35f0-11ea-8eba-7bebc731a6a9.png)

![2](https://user-images.githubusercontent.com/5305782/72245514-0544b200-35f1-11ea-8f8c-36835d06203d.png)

![Screen Shot 2020-01-12 at 12 28 52](https://user-images.githubusercontent.com/5305782/72245522-0c6bc000-35f1-11ea-9eb2-6afadeafe445.png)

![Screen Shot 2020-01-12 at 12 29 25](https://user-images.githubusercontent.com/5305782/72246637-738a7400-35f3-11ea-88a0-7c199c700d83.png)

**Comment by ABogstad** [comment]
Update: 
The black background is not a button behind the Vipps button, The black area is part of div element vipps-express-checkout and when pressing on the black (or none background) area, redirects another page with url pmnorwegia.no/undefined

See the following images, the last images (44.png) show where the issue are. I believe the issue are as follow: the width (280 px) of div.vipps-express-checkout is greater than vipps-checkout (svg width=253px). The whole area div.vipps-express-checkout is a button area, only vipps-checkout area with the vipps orange button image has defined actions connected to it. The rest of the button area on the left side 23.5px and right side 23.5px (280-253=27/2=23.5) have no actions defined for it. Hence, when those area are pressed on they redirects to error 404 page with the URL www.fgsfgsfsfds.no/undefined

Removing the background with code: 

 

.block-minicart .block-content>.actions a.vipps-checkout{

background:none;

}

Press on the are where the background colour is none redirects  404 error page with url www.gdfgghs.no/undefined

![2](https://user-images.githubusercontent.com/5305782/73062068-cdb0f200-3e9b-11ea-9ca6-118156903dd7.png)

![44](https://user-images.githubusercontent.com/5305782/73062096-dd303b00-3e9b-11ea-93ce-da2c6396ee7a.png)

**Comment by ABogstad** [comment]
Hi thank you for your solution, I have one question.  You commited the code change in files Gateway/Response/TransactionHandler.php in e33752b, however in edff02f you committed Model/OrderPlace.php and not Gateway/Response/TransactionHandler.php.

Which solution should I use, the latest edff02f?

**Comment by ed007m** [comment]
@ABogstad , I'm resolving this issue currently. And will merge this branch to master.

**Comment by ed007m** [comment]
@ABogstad, please check our latest code changes which includes fixes for you issue.
master branch for magento 2.2.x (composer version 1.2.10)
1.3 branch for magento 2.3.x (composer version 1.3.10)

**Comment by ABogstad** [comment]
It works good now, great work! :)
