### ISSUE TITLE
Support for Klarna Checkout on Magento 1

### ISSUE THREAD

**Issue by cloveras** [vippsas/vipps-magento#55]
On behalf of a customer:

> We could not use the Magento 2 extension for KCO with Magento 1. We no longer use Vaimo extension, now we use Klarna offical extension from Klarna with KCOv3.

**Comment by ABogstad** [comment]
I believe you are on wrong place with this issue, please see https://github.com/klarna

**Comment by voleye** [comment]
Compatibility with Klarna Checkout was added in all versions of Module (2.2, 2.3, 1.x)
Please, check latest releases:
 - https://github.com/vippsas/vipps-magento/releases
 - https://github.com/vippsas/vipps-magento-v1/releases

I closed this issue
