### ISSUE TITLE
cancellation not working, Magento 1.9

### ISSUE THREAD

**Issue by JanD-work** [vippsas/vipps-magento#58]
We have been troubleshooting the module in Magneto 1.9 as we had problems that cancellation was not send. We found the following. Could you please verify if this is an issue and a correct solution to it: 
![image](https://user-images.githubusercontent.com/60696847/73841856-ba970e00-481b-11ea-965e-84147420e65d.png)

**Comment by cloveras** [comment]
Hi

This has now been fixed, in release 1.0.4: https://github.com/vippsas/vipps-magento-v1/releases

Thank you very much for reporting this, and helping us improve the solution.

Christian, Vipps

**Comment by voleye** [comment]
Since this issue solved I will close it
