### ISSUE TITLE
ReferenceError: event is not defined

### ISSUE THREAD

**Issue by DrKoolaid** [vippsas/vipps-magento#6]
I have Magento 2.2.5 and latest version of this module.

But when selecting "vipps" in the checkout and clicking "Continue to Vipps", it just reloads and I get the error:
ReferenceError: event is not defined
vipps.min.js:53:17

I have tried adding "event" so it becomes
continueToVipps: function (event) {

but then I get:
TypeError: event.preventDefault is not a function

I am using the Porto template and Amasty One page checkout, but have tried using Magento standard checkout whit same results.

**Comment by voleye** [comment]
@DrKoolaid thank you for your report. We will take a look on it and get back to you soon

**Comment by ed007m** [comment]
Thanks @DrKoolaid for reporting your issue. It has been fixed in our lates 1.0.3 release.
