### ISSUE TITLE
Support Magento 2.4.0

### ISSUE THREAD

**Issue by pikulsky** [vippsas/vipps-magento#69]
Hi,
What about support Magento 2.4.0 ?
Is there any plans/ETA on this?

**Comment by ed007m** [comment]
Hi,
We are planning to publish compatible version in the end of next week.

**Comment by pikulsky** [comment]
Great news! Thank you, we will look forward to it!

**Comment by ed007m** [comment]
@pikulsky 
We have published vipps:2.4.0 compatible with Magento 2.4.x
https://github.com/vippsas/vipps-magento/releases/tag/2.4.0

**Comment by pikulsky** [comment]
@ed007m , thank you!
