### ISSUE TITLE
Not found class

### ISSUE THREAD

**Issue by hryvinskyi** [vippsas/vipps-magento#74]
https://github.com/vippsas/vipps-magento/blob/c62412652c243dccd156a29fa38661572033c655/Controller/Payment/RegularRedirect.php#L28

Regular Class not exist

**Comment by ed007m** [comment]
Hi, @hryvinskyi 
I've removed this file since it is not used.

**Comment by hryvinskyi** [comment]
@ed007m 

Please create new tag and release, becouse we cant generate dependency injections

**Comment by hryvinskyi** [comment]
@ed007m are you aware that version 2.4.1 is not working due to this problem? how do you think it will work on magento cloud if the class does not exist?.

**Comment by ed007m** [comment]
@hryvinskyi 
We have published a new release https://github.com/vippsas/vipps-magento/releases/tag/2.4.2

**Comment by hryvinskyi** [comment]
@ed007m thank you
