### ISSUE TITLE
Whole payment capture issue

### ISSUE THREAD

**Issue by tereshvti** [vippsas/vipps-magento#87]
Creating online invoice in Magento with order line total 0 results in the whole payment amout(remaining) capture in VIPPS.
Order item price can be set to 0 with cart rule for example. Invoice can contain only this order item

**Comment by cloveras** [comment]
Hi @tereshvti 

Just a comment before the developers reply here: Our API requires payments to be larger than zero: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#regular-ecommerce-payments

There is no "invoice" functionality in our eCom API, we call it "capture". You first initiate a payment, then the users confirms in Vipps so the payment is reserved, and then you make the capture call. See the call-by-call info: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#call-by-call-guide

If the payment amount is 0 kr, there is no way to use Vipps to "pay" the zero kroner.

Christian, Vipps

**Comment by ed007m** [comment]
Hi @tereshvti 

For better understanding this case could you, please, describe next info:
- magento edition/version, php version, vipps payment module versions;
- presets that should be done to reproduce an issue;
- steps to reproduce and expected results.

It would be much easy for us to define a case.
