### ISSUE TITLE
Magento 2.4.2 and Vipps 2.4.7 module. Cart quote is not restored on payment cancellation.

### ISSUE THREAD

**Issue by bitforbucket** [vippsas/vipps-magento#92]
Magento 2.4.2 and Vipps 2.4.7 module. Cart quote is not restored when you cancel Vipps payment in checkout. User redirected to failure page instead of cart page and cart quote is empty.

**Comment by ed007m** [comment]
@bitforbucket 
Thank you for your request. In the latest [Vipps 2.3.16](https://github.com/vippsas/vipps-magento/releases/tag/2.3.16) release which is compatible with M2.3 - we have added a new functionality for restoring a quote functionality. However, this functionality has not yet been implemented to Vipps 2.4.x. We are working on it and expect it to be available in 1-2 weeks.

**Comment by ed007m** [comment]
@bitforbucket 
We have implemented restoring quote functionality for M2.4.x [in Vipps 2.4.8.](https://github.com/vippsas/vipps-magento/releases/tag/2.4.8).
